<?xml version="1.0"?>
<package format="3">
  <name>simrad_halo_driver_v2</name>
  <version>0.0.0</version>
  <description>
    Driver for the Simrad Halo series of marine radars
  </description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>GPL</license>
  
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rosidl_default_generators</build_depend>
  <doc_depend>doxygen</doc_depend>
  <depend>ament_index_cpp</depend>
  <depend>builtin_interfaces</depend>
  <depend>marine_radar_control_msgs</depend>
  <depend>marine_sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rosbag2</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
